### ISSUE TITLE
Take bed offset into account

### ISSUE THREAD

**Issue by rijobro** [CCPPETMR/Hackathon-STIR#13]
- [x] Store bed offset in InterfileHeader. Default = 0.
- [x] Add to InterfileSiemensHeader (reader and writer, but just reader initially).
- [x] Set/get functions in ProjDataInfo.
- [x] Implement offset in MatrixRayTracing.
- [x] `offset_in_z` already taken into account, modification would be `offset_in_z+/-bed_offset`.
- [ ] Test by altering the header of a sinogram (e.g., `bed_offset (mm):= 30`). Reconstruct. Has the image moved by 30 mm in Slicer?
- [ ] Has it moved 30 mm in the right direction? To test this, we probably need two acquisitions, where the only difference between the two is the bed position. If the two images line up, great! If not, try flipping the +/-.

**Comment by KrisThielemans** [comment]
See https://github.com/UCL/STIR/issues/219

**Comment by ashgillman** [comment]
This is/will be covered by https://github.com/UCL/STIR/projects/1

**Comment by ashgillman** [comment]
This extended beyond hackathon and is covered by https://github.com/UCL/STIR/projects/1
